### ISSUE TITLE
No error, after compiling, but not starting simulation through omnetpp.ini either 

### ISSUE THREAD

**Issue by l4mbd0x** [michaelkirsche/IEEE802154INET-Standalone#1]
After compiling the Omnet 4.3 with INET 4.6(everything compiled perfectly) but when the omnetpp is requested to Run as a simulation on OMNeT++. It does try to start and after progressing 50% it stops as follows:

Starting...

$ cd C:/Users/Nicolas/Downloads/IEEE802154INET-Standalone-master/simulations
$ ../src/IEEE802154INET-Standalone.exe -r 0 -n ../src;.;../../inet-2.6-src/inet/examples;../../inet-2.6-src/inet/src -l ../../inet-2.6-src/inet/src/inet omnetpp.ini

Simulation terminated with exit code: -1073741819
Working directory: C:/Users/Nicolas/Downloads/IEEE802154INET-Standalone-master/simulations
Command line: ../src/IEEE802154INET-Standalone.exe -r 0 -n ../src;.;../../inet-2.6-src/inet/examples;../../inet-2.6-src/inet/src -l ../../inet-2.6-src/inet/src/inet omnetpp.ini

Environment variables:
OMNETPP_ROOT=c:/omnetpp-4.3
PATH=;C:/Users/Nicolas/Downloads/inet-2.6-src/inet/src;c:\omnetpp-4.3\bin;c:\omnetpp-4.3\msys\bin;c:\omnetpp-4.3\mingw\bin;c:/omnetpp-4.3/ide/jre/bin/client;c:/omnetpp-4.3/ide/jre/bin;c:/omnetpp-4.3/ide/jre/lib/i386;.;C:\omnetpp-4.3\msys\local\bin;c:\omnetpp-4.3\mingw\bin;C:\omnetpp-4.3\msys\bin;c:\omnetpp-4.3\bin;c:\ProgramData\Oracle\Java\javapath;c:\Windows\system32;c:\Windows;c:\Windows\System32\Wbem;c:\Windows\System32\WindowsPowerShell\v1.0\;c:\Program Files (x86)\Skype\Phone\;c:\omnetpp-4.3;
OMNETPP_IMAGE_PATH=c:\omnetpp-4.3\images

---

The error is shown in the third image.
![img1](https://cloud.githubusercontent.com/assets/14299648/11325095/022e05f8-912c-11e5-8804-d233c403bcd2.png)
![img2](https://cloud.githubusercontent.com/assets/14299648/11325096/022fe472-912c-11e5-8257-b56be9e4e446.png)
![img3](https://cloud.githubusercontent.com/assets/14299648/11325097/02334b44-912c-11e5-897d-343145f38c8f.png)

**Comment by michaelkirsche** [comment]
If you haven't found the source of the error yet, it is pretty simple: signal checking was introduced in OMNeT++ 4.4.1, so your version of OMNeT is a bit outdated. I'd recommend to use OMNeT 4.6.

**Comment by l4mbd0x** [comment]
Hello Michael,

Yes I solved my issue already.

**Comment by orion9009** [comment]
hello lambd0x... how your solve those problem ?

 I`m currently using omnet++ 4.6 with inet 2.6 encounter same issues related to environment variable while running the simulation..

**Comment by l4mbd0x** [comment]
Hello orion9009, one year ago after having some trouble with OMNeT++ version 4.3 I decided to try all the other versions available at that time to be sure I wasn't the one doing something wrong, end up that the test version in Downloads at that time helped me get it working. But since today OMNeT++ has 5.0 version, test it alongside all the dependencies up to date while compiling the software. If it doesn't work, then reopen this issue or create another one specific to the very problem you still get to face. Hope this helps you. BTW.

**Comment by orion9009** [comment]
During that time, what omnet++ version that you used and also the inet
framework version?

**Comment by l4mbd0x** [comment]
Hi, orion9009. they removed the test version that was available on year ago from the OMNeT++. So I can't confirm for you the one I used, although since version 4.3 used to be the latest release and now they got version 4.4.1 and others that wasn't available back then. I assume 4.4.1 would be equivalent to that test version and related to INET, it's the 2.6.0 version for OMNeT++ 4.4 for sure.

**Comment by orion9009** [comment]
It's ok.. thank you for the info.
