### ISSUE TITLE
Error in Building

### ISSUE THREAD

**Issue by clausava2** [michaelkirsche/IEEE802154INET-Standalone#2]
Hi,
I successfully work on Omnet++ 4.6 and Inet 3.1 but I would like to simulate 802.15.4 networks with your project. I downloaded and extracted the code, I imported it in Omnet++ and from >>properties>>reference project I selected my Inet installation. When I try to build the project several errors occur. Any help?
Thanks 
Claudio

**Comment by michaelkirsche** [comment]
Just saw this issue, although it is a bit late, you saw the requirements of the standalone model? INET 2.x version (tested with 2.2 to 2.6). So INET 3.1 will not work with the old release of the model.
