### ISSUE TITLE
Add wifi module in to the model

### ISSUE THREAD

**Issue by orion9009** [michaelkirsche/IEEE802154INET-Standalone#3]
Can I add wifi module from INET framework into the IEEE 802.15.4 model, is it possible? .  I`m required to simulate coexistence between  IEEE 802.15.4 and WLAN in term of throughput and packet loss.

**Comment by michaelkirsche** [comment]
Not with the version 2.6 or 2.x of INET (and thus not with the current state of this IEEE 802.15.4 model).
Coexistence of multiple wireless technologies might work with INET 3.x, which does contain a newly designed IEEE 802.11 MAC models, various PHY models, and a IEEE 802.15.4 model.
