### ISSUE TITLE
Error while compile the project.

### ISSUE THREAD

**Issue by josebeo2016** [michaelkirsche/IEEE802154INET-Standalone#4]
Hi
I use inet 2.6 with omnet++ 4.6. When I compile, some errors occur:
In file included from Modules/IEEE802154Radio.cc:24:0:
Modules/IEEE802154Radio.h:25:27: fatal error: ChannelAccess.h: No such file or directory
 #include "ChannelAccess.h"
                           ^
compilation terminated.
Makefile:120: recipe for target '../out/gcc-debug/src/Modules/IEEE802154Radio.o' failed
make[1]: *** [../out/gcc-debug/src/Modules/IEEE802154Radio.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from Modules/IEEE802154Mac.cc:20:0:
Modules/IEEE802154Mac.h:38:77: fatal error: RadioState.h: No such file or directory
 #include "RadioState.h"             // from INET - provides RadioState enums
                                                                             ^
compilation terminated.
In file included from Modules/llc.cc:19:0:
Modules/llc.h:28:25: fatal error: IPvXAddress.h: No such file or directory
 #include "IPvXAddress.h"
                         ^
compilation terminated.
Makefile:120: recipe for target '../out/gcc-debug/src/Modules/IEEE802154Mac.o' failed
make[1]: *** [../out/gcc-debug/src/Modules/IEEE802154Mac.o] Error 1
Makefile:120: recipe for target '../out/gcc-debug/src/Modules/llc.o' failed
make[1]: *** [../out/gcc-debug/src/Modules/llc.o] Error 1
make[1]: Leaving directory '/c/omnetpp-4.6/git/IEEE802154INET-Standalone/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

Please help me to fix it.
Thanks alot

**Comment by michaelkirsche** [comment]
Did you check the installation steps from the README.md?
Did you select your INET 2.6 installation as a "project reference"??

**Comment by josebeo2016** [comment]
![image](https://user-images.githubusercontent.com/24622450/33557768-b7d4c4b6-d93a-11e7-9110-b895958b85fd.png)
Yes I've.

**Comment by michaelkirsche** [comment]
So you have an open INET project named "project" and a closed or non-existing one named "inet-2.6". The second one is linked as a referenced project. But the first one should be your reference project, closed or non-existing projects cannot be compiled or linked against. Check and use the other "inet" project.

**Comment by josebeo2016** [comment]
I've tried to use "inet" project instead of "inet-2.6" but it still have many error. 
I've looked for ChannelAccess.h in my Omnetpp project folder but not found. Can you please help me show me the right way to install omnet 4.x and inet2.x suit for this project.
Thanks

**Comment by michaelkirsche** [comment]
Did you really follow all the instructions of the README.md?
Steps are really easy... 
1. Install OMNeT++ 4.6
2. Import INET 2.6, select the necessary minimal feature set
3. Import the 802.15.4 Standalone project
4. Select the right INET project as the project reference
5. Build INET and 802.15.4 project

Nothing that is not written and explained in the README.md.

**Comment by josebeo2016** [comment]
I've solved my problem by reinstall inet. I realize that the inet version is not real 2.6.
Thank you for your great help.
