### ISSUE TITLE
Error when running INET on OMNET++5.4.1 

### ISSUE THREAD

**Issue by Farhadesfandiar** [michaelkirsche/IEEE802154INET-Standalone#6]
Hello everyone, usually I find best answer here. I installed omnet++5.4.1 on Ubuntu18 on my Virtual machine. Then I installed INET automatically by omnet.( Help\Install simulation models).
After building( which is successful) when I'm running INET as an omnet simulation, I face below error. 
I will appreciate any kind answer. Thankyou

<!> Error: Cannot load library '../../../src//libINET.so': ../../../src//libINET.so: undefined symbol: _ZTIN3osg5GroupE

End.

Simulation terminated with exit code: 1
Working directory: /home/ali/omnetpp-5.4.1/samples/inet4/examples/wireless/dynamic
Command line: opp_run -m -n ../../../src:../..:../../../tutorials:../../../showcases --image-path=../../../images -l ../../../src/INET omnetpp.ini

Environment variables:
PATH=/home/ali/omnetpp-5.4.1/bin::/home/ali/omnetpp-5.4.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/home/ali/omnetpp-5.4.1/lib::/home/ali/omnetpp-5.4.1/samples/inet4/src:
OMNETPP_IMAGE_PATH=/home/ali/omnetpp-5.4.1/images

**Comment by michaelkirsche** [comment]
This OSG issue is not related to the INET 2.x based 802.15.4 simulation model. I'll close this issue therefore.
You can find help on the OMNeT++ mailing list / Google group.

**Comment by mygtaba96** [comment]
hi  i have the  same error when i run inet framework  simulation  on omnet++ 5.1.1 on  my device  windows 7  

Simulation terminated with exit code: 1
Working directory: M:/inet-4.1.1-src/inet4/examples/bgpv4/Bgp2RoutersInAS
Command line: C:/omnetpp-5.1.1/bin/opp_run.exe -m -n ../../../src;../..;../../../tutorials;../../../showcases --image-path=../../../images -l ../../../src/INET omnetpp.ini

Environment variables:
PATH=;M:/inet-4.1.1-src/inet4/src;C:\omnetpp-5.1.1\bin;C:\omnetpp-5.1.1\tools\win64\mingw64\bin;C:\omnetpp-5.1.1\tools\win64\usr\bin;;C:/omnetpp-5.1.1/ide/jre/bin/server;C:/omnetpp-5.1.1/ide/jre/bin;C:/omnetpp-5.1.1/ide/jre/lib/amd64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\omnetpp-5.1.1\ide;
OMNETPP_IMAGE_PATH=C:\omnetpp-5.1.1\images
